name: Build
description: Build frontend image

inputs:
  aws-secret-key:
    required: true
  aws-access-key-id:
    required: true
  aws-region:
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push the image to Amazon ECR
      shell: bash
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        RUNNER_ID: ${{ github.run_number }}
      run: |
        IMAGE_TAG=build-$PROJECT-$RUNNER_ID
        docker build --build-arg ENVIRONMENT=$ENVIRONMENT -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . # TODO: build from cache
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "New image name=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
