name: Finish deploying
description: Notify end deploying

inputs:
  slack-webhook-url:
    required: true
  update-deployment-result:
    required: true

runs:
  using: composite
  steps:
    - name: Set up environment variables
      shell: bash
      run: |
        echo "CI_JOB_URL=${{ github.event.head_commit.url }}" >> $GITHUB_ENV
        echo "GITHUB_USER_NAME=${{ github.actor }}" >> $GITHUB_ENV
        echo "CI_COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
        echo "UPDATE_DEPLOYMENT_RESULT=${{ inputs.update-deployment-result }}" >> $GITHUB_ENV

    - name: Send slack notification
      shell: bash
      run: |
        escape() {
          VALUE=${1//\//""}
          VALUE=${VALUE//\"/""}
          VALUE=${VALUE//\\/""}
          echo $VALUE
        }

        sendMessage() {
          local COLOR=$1
          local CONTENT=$(escape "${2}")
          local MESSAGE='{
            "attachments": [
              {
                "color": "'$COLOR'",
                "title": "'$CONTENT'",
                "title_link": "'$CI_JOB_URL'",
                "text": ":farmer: *'$GITHUB_USER_NAME'* committed.\n\n```\n'${CI_COMMIT_MESSAGE}'\n```"
              }
            ],
            "username": "Deployment Bot"
          }'
          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" ${{ inputs.slack-webhook-url }}
        }

        if [ "${{ inputs.update-deployment-result }}" == "success" ]; then
          COLOR='#36A64F' # success color
          sendMessage "$COLOR" "Deployed to $ENVIRONMENT successfully :rocket: :rocket: :rocket:"
        else
          COLOR='#FF0000' # danger color
          sendMessage "$COLOR" "Deployed to $ENVIRONMENT failed :skull_and_crossbones: :exploding_head: :hear_no_evil:"
        fi
