name: Update deployment
description: Update image in deployment repo

runs:
  using: composite
  steps:
    - name: Set up Git user
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone deployment repository
      shell: bash
      run: git clone $REPOSITORY_URL

    - name: Update image in values.yaml
      shell: bash
      env:
        RUNNER_ID: ${{ github.run_id }}
      run: |
         IMAGE_TAG=build-$PROJECT-$RUNNER_ID
         cd $HELM_DEPLOYMENT_DIRECTORY
         sed -i "s|tag: build-$PROJECT-[0-9]\+|tag: $IMAGE_TAG|" $HELM_CHART_NAME.yaml

    - name: Commit and Push changes
      shell: bash
      run: |
        cd $REPOSITORY_NAME
        git add "environments/$ENVIRONMENT/$HELM_CHART_NAME.yaml"
        git commit -m "[$ENVIRONMENT][$HELM_CHART_NAME] Pipeline #$GITHUB_RUN_NUMBER: ${{ github.event.head_commit.message }}"
        git push
